# Generated by Django 4.0.1 on 2022-01-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('other', 'Другое'), ('TV', 'Телевизоры'), ('notebooks', 'Ноутбуки'), ('telephone', 'Телефоны'), ('keyboard', 'Клавиатуры'), ('monitors', 'Мониторы'), ('pc', 'компьютеры')], default='other', max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, max_length=10, verbose_name='Цена'),
        ),
    ]
